# Omarchy Void Linux repositories
repository=https://repo-fastly.voidlinux.org/current
repository=https://repo-fastly.voidlinux.org/current/multilib
repository=https://repo-fastly.voidlinux.org/current/nonfree
repository=https://repo-fastly.voidlinux.org/current/multilib/nonfree
repository=https://raw.githubusercontent.com/Makrennel/hyprland-void/repository-x86_64-glibc
