# Detect T2 MacBook models using PCI IDs
# Vendor: 106b (Apple), Device IDs: 1801 or 1802 (T2 Security Chip)
if lspci -nn | grep -q "106b:180[12]"; then
  echo "Detected MacBook with T2 chip. Installing support items..."

  omarchy-pkg-add \
    linux-t2 \
    linux-t2-headers \
    apple-t2-audio-config \
    apple-bcm-firmware

  # FIXME: t2fanrd and tiny-dfr may not be available in Void Linux repositories.
  # Uncomment these if/when packages become available.
  # omarchy-pkg-add t2fanrd tiny-dfr

  # Add user to video group (required for tiny-dfr to access /dev/dri devices)
  sudo usermod -aG video ${USER}

  # Enable T2 services (Void Linux uses runit)
  if omarchy-cmd-present sv; then
    if omarchy-pkg-present t2fanrd; then
      sudo ln -sf /etc/sv/t2fanrd /var/service/
    fi
    if omarchy-pkg-present tiny-dfr; then
      sudo ln -sf /etc/sv/tiny-dfr /var/service/
    fi
  fi

  echo "apple-bce" | sudo tee /etc/modules-load.d/t2.conf >/dev/null
  echo "hci_bcm4377" | sudo tee -a /etc/modules-load.d/t2.conf >/dev/null

  # Dracut drop-in for initramfs modules (Void uses dracut, not mkinitcpio)
  sudo mkdir -p /etc/dracut.conf.d
  cat <<EOF | sudo tee /etc/dracut.conf.d/apple-t2.conf >/dev/null
# Generated by Omarchy installer for T2 Mac support
add_drivers+=" apple-bce usbhid hid_apple hid_generic xhci_pci xhci_hcd "
EOF

  cat <<EOF | sudo tee /etc/modprobe.d/brcmfmac.conf >/dev/null
# Fix for T2 MacBook WiFi connectivity issues
options brcmfmac feature_disable=0x82000
EOF

  # GRUB kernel command line for T2 Mac support
  GRUB_DEFAULT="/etc/default/grub"
  if [[ -f $GRUB_DEFAULT ]]; then
    if ! grep -q "intel_iommu=on" "$GRUB_DEFAULT"; then
      sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on iommu=pt pcie_ports=compat"/' "$GRUB_DEFAULT"
    fi
  fi

  cat <<EOF | sudo tee /etc/t2fand.conf >/dev/null
[Fan1]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false
EOF
fi
