# Detect MacBook models that need SPI keyboard modules
product_name="$(cat /sys/class/dmi/id/product_name 2>/dev/null)"
if [[ $product_name =~ MacBook[89],1|MacBook1[02],1|MacBookPro13,[123]|MacBookPro14,[123] ]]; then
  echo "Detected MacBook with SPI keyboard"

  omarchy-pkg-add macbook12-spi-driver-dkms

  # Dracut drop-in for initramfs modules (Void uses dracut, not mkinitcpio)
  sudo mkdir -p /etc/dracut.conf.d
  if [[ $product_name == "MacBook8,1" ]]; then
    cat <<EOF | sudo tee /etc/dracut.conf.d/macbook_spi_modules.conf >/dev/null
# Generated by Omarchy installer for MacBook SPI keyboard support
add_drivers+=" applespi spi_pxa2xx_platform spi_pxa2xx_pci "
EOF
  else
    cat <<EOF | sudo tee /etc/dracut.conf.d/macbook_spi_modules.conf >/dev/null
# Generated by Omarchy installer for MacBook SPI keyboard support
add_drivers+=" applespi intel_lpss_pci spi_pxa2xx_platform "
EOF
  fi
fi
